apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: service-accounts
spec:
  serviceAccountName: myserviceaccount
  containers:
  - name: my-container
    image: 1d3r3r/k8svcacctest:latest
    imagePullPolicy: Always
  nodeName: virtual-node-aci-linux
