apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: myserviceaccount-token
  namespace: service-accounts
  annotations:
    kubernetes.io/service-account.name: myserviceaccount